name: Testing

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
      - stage

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: pre-commit
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20"
      - name: build and testing
        run: |
          go version
          go test -v ./...
          go build -ldflags="-s -w" -o clotho cmd/clotho/main.go
